const PROVENANCE_SCHEMA = {
  type: "object",
  description: "Provenance object from caller (invocation_id, provider, model, reasoning, was_fallback, source_path, timestamp)",
  properties: {
    invocation_id: { type: "string", format: "uuid" },
    provider: { type: "string" },
    model: { type: "string" },
    reasoning: { type: "string" },
    was_fallback: { type: "boolean" },
    source_path: { type: "string" },
    timestamp: { type: "string" },
  },
};

export const MEMORY_TOOL_DEFINITIONS = [
  {
    name: "capture_memory",
    description: "Store a memory item (thought, decision, context, lesson) with auto-embedding and deduplication",
    inputSchema: {
      type: "object" as const,
      properties: {
        content: { oneOf: [{ type: "string" }, { type: "object" }], description: "Content to store" },
        content_type: {
          type: "string",
          enum: [
            "text",
            "decision",
            "intent",
            "context",
            "lesson",
            "convention",
            "requirement",
            "note",
            "open_loop",
            "artifact_ref",
            "rule",
            "role",
            "setting",
            "finding",
          ],
          default: "text",
        },
        scope: { type: "string", description: "Scope path (org/project/initiative/phase/thread)" },
        tags: { type: "array", items: { type: "string" }, default: [] },
        trust_level: { type: "string", enum: ["working", "reviewed", "locked"], default: "working" },
        skip_dedup: { type: "boolean", default: false },
        provenance: PROVENANCE_SCHEMA,
      },
      required: ["content", "scope", "provenance"],
    },
  },
  {
    name: "search_memory",
    description: "Hybrid semantic + keyword search across memory items",
    inputSchema: {
      type: "object" as const,
      properties: {
        query: { type: "string", description: "Search query" },
        scope: { type: "string", description: "Scope path to filter" },
        content_type: {
          type: "string",
          enum: [
            "text",
            "decision",
            "intent",
            "context",
            "lesson",
            "convention",
            "requirement",
            "note",
            "open_loop",
            "artifact_ref",
            "rule",
            "role",
            "setting",
            "finding",
          ],
        },
        content_types: {
          type: "array",
          items: {
            type: "string",
            enum: [
              "text",
              "decision",
              "intent",
              "context",
              "lesson",
              "convention",
              "requirement",
              "note",
              "open_loop",
              "artifact_ref",
              "rule",
              "role",
              "setting",
              "finding",
            ],
          },
        },
        trust_levels: {
          type: "array",
          items: { type: "string", enum: ["working", "reviewed", "locked"] },
        },
        semantic_weight: { type: "number", minimum: 0, maximum: 1, default: 0.7 },
        max_results: { type: "number", minimum: 1, maximum: 100, default: 10 },
        include_legacy: { type: "boolean", default: false },
        provenance: PROVENANCE_SCHEMA,
      },
      required: ["query", "scope"],
    },
  },
  {
    name: "get_context_summary",
    description: "Get priority-sorted context summary for a scope",
    inputSchema: {
      type: "object" as const,
      properties: {
        scope: { type: "string" },
        content_type: { type: "string" },
        limit: { type: "number", default: 50 },
        include_legacy: { type: "boolean", default: false },
        provenance: PROVENANCE_SCHEMA,
      },
      required: ["scope"],
    },
  },
  {
    name: "list_recent",
    description: "List recent memory items with pagination",
    inputSchema: {
      type: "object" as const,
      properties: {
        scope: { type: "string" },
        content_type: { type: "string" },
        limit: { type: "number", default: 20 },
        offset: { type: "number", default: 0 },
        include_legacy: { type: "boolean", default: false },
        provenance: PROVENANCE_SCHEMA,
      },
      required: ["scope"],
    },
  },
  {
    name: "memory_manage",
    description: "Delete, archive, supersede, update tags, change trust level, or publish a finalized requirement artifact",
    inputSchema: {
      type: "object" as const,
      properties: {
        action: {
          type: "string",
          enum: ["delete", "archive", "supersede", "update_tags", "update_trust_level", "publish_finalized_requirement"],
        },
        memory_id: { type: "string", format: "uuid" },
        scope: { type: "string", description: "Scope path that must own the target memory item" },
        tags: { type: "array", items: { type: "string" } },
        trust_level: { type: "string", enum: ["working", "reviewed", "locked"] },
        reason: { type: "string" },
        provenance: PROVENANCE_SCHEMA,
      },
      required: ["action", "memory_id", "scope", "provenance"],
    },
  },
];
